services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstack
      - MYSQL_ROOT_PASSWORD=hkdigitals
    volumes:
      - maria_db_data:/config
    networks:
      - shared-network
    ports:
      - 3306:3306

  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack-app
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - APP_URL=https://wiki.teleese.com
      - APP_KEY=base64:YhBm9PfiYZ2IykR/onFGhwPq0xDf7POmkvMqmudU7xI=
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_USERNAME=bookstack
      - DB_PASSWORD=bookstack
      - DB_DATABASE=bookstack
    ports:
      - 6875:80
    volumes:
      - ./config:/config
    depends_on:
      - mariadb
    networks:
      - shared-network

volumes:
  maria_db_data:
    external: true
    name: docker-deployment-templates_maria_db_data

networks:
  shared-network:
    external: true
