services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_DATABASE={MYSQL_DATABASE}
      - MYSQL_USER={MYSQL_USER}
      - MYSQL_PASSWORD={MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD={MYSQL_ROOT_PASSWORD}
    volumes:
      - maria_db_data:/config
    networks:
      - shared-network
    ports:
      - 3306:3306

  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack-app
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - APP_URL={APP_URL}
      - APP_KEY={APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_USERNAME={DB_USERNAME}
      - DB_PASSWORD={DB_PASSWORD}
      - DB_DATABASE={DB_DATABASE}
    ports:
      - 6875:80
    volumes:
      - ./config:/config
    depends_on:
      - mariadb
    networks:
      - shared-network

volumes:
  maria_db_data:

networks:
  shared-network:
    external: true
