services:
  odoo:
    image: odoo:latest
    container_name: odoo
    restart: unless-stopped
    networks:
      - shared-network
    ports:
      - "8069:8069"
      - "8071:8071"
      - "8072:8072"
    environment:
      - HOST=postgres
      - PORT=5432
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - odoo_data:/var/lib/odoo
      - ./config/odoo/odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/extra-addons

volumes:
  odoo_data:
    external: true
    name: docker-deployment-templates_odoo_data

networks:
  shared-network:
    external: true
