services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/file_sd:/etc/prometheus/file_sd
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - shared-network

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki/loki-config.yml:/etc/loki/loki-config.yml
      - ./loki:/loki
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - shared-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./config/loki/promtail-config.yml:/etc/promtail/config.yml
      - ./config/loki/logs_sd:/etc/promtail/logs_sd
      - ./logs:/var/log/projects
    command: -config.file=/etc/promtail/config.yml
    networks:
      - shared-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
     - ${GF_PORT}:3000
    environment:
    - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
    - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - shared-network
    
volumes:
  grafana-data:
    external: true

networks:
  shared-network:
    external: true
