server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: file_sd_targets
    file_sd_configs:
      - files:
          - /etc/promtail/logs_sd/*.yml
        refresh_interval: 30s
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}T[^ ]+) (?P<level>[A-Z]+) (?P<pid>\d+) --- \[(?P<app>[^\]]+)] \[(?P<thread>[^\]]+)] (?P<class>[^\s]+)\s+: (?P<message>.*)'
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          values:
            - level
            - app
            - thread
            - class
